-- Quo router will write intake fields as plain columns on public.intakes (not jsonb / intakes_flat).
-- Keep `data` for legacy rows; DocketFlow prefers plain columns and falls back to jsonb when null.

alter table public.intakes
  add column if not exists how_found text,
  add column if not exists map_location text,
  add column if not exists accident_time text,
  add column if not exists representation_date text,
  add column if not exists accident_location text,
  add column if not exists city text,
  add column if not exists county text,
  add column if not exists accident_description text,
  add column if not exists police_department text,
  add column if not exists police_report_no text,
  add column if not exists ticket_issued boolean,
  add column if not exists ticket_who text,
  add column if not exists ticket_reason text,
  add column if not exists email text,
  add column if not exists address text,
  add column if not exists dob text,
  add column if not exists sex text,
  add column if not exists dl_number text,
  add column if not exists spouse_name text,
  add column if not exists emergency_contact text,
  add column if not exists passengers text,
  add column if not exists vehicle text,
  add column if not exists vehicle_owner text,
  add column if not exists drivable boolean,
  add column if not exists towed boolean,
  add column if not exists towed_by text,
  add column if not exists vehicle_location text,
  add column if not exists has_loan boolean,
  add column if not exists lienholder text,
  add column if not exists rental_needed boolean,
  add column if not exists body_shop text,
  add column if not exists employer text,
  add column if not exists job_description text,
  add column if not exists missed_work boolean,
  add column if not exists salary_rate text,
  add column if not exists other_driver_name text,
  add column if not exists other_driver_phone text,
  add column if not exists other_driver_dob text,
  add column if not exists other_driver_address text,
  add column if not exists other_driver_dl text,
  add column if not exists other_driver_car_owner text,
  add column if not exists client_insurance text,
  add column if not exists client_policy_no text,
  add column if not exists client_claim_no text,
  add column if not exists third_party_insurance text,
  add column if not exists third_party_policy_no text,
  add column if not exists third_party_claim_no text,
  add column if not exists pip boolean,
  add column if not exists med_pay boolean,
  add column if not exists um_uim boolean,
  add column if not exists ems boolean,
  add column if not exists hospital_bill boolean,
  add column if not exists hospital text,
  add column if not exists treating_doctor text,
  add column if not exists injury_types text,
  add column if not exists medicaid boolean,
  add column if not exists medicare boolean,
  add column if not exists health_insurance text,
  add column if not exists notes text;

comment on table public.intakes is
  'Call intakes. Quo router writes plain columns (fill-empty only). DocketFlow edits via normal UPDATEs.';
